# Generated by Django 4.0.3 on 2022-12-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('os', models.CharField(default='', max_length=250)),
                ('browser', models.CharField(default='', max_length=250)),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'visitors',
            },
        ),
    ]
