# Generated by Django 4.0.3 on 2022-12-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'visitors',
            },
        ),
    ]
