# Generated by Django 4.0.3 on 2022-08-15 11:35

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=251, unique=True)),
                ('my_bulls', models.IntegerField(null=True)),
                ('my_cows', models.IntegerField(null=True)),
                ('my_guess', models.CharField(max_length=10, null=True)),
                ('my_number', models.CharField(max_length=10, null=True)),
                ('your_bulls', models.IntegerField(null=True)),
                ('your_cows', models.IntegerField(null=True)),
                ('your_guess', models.CharField(max_length=10, null=True)),
                ('your_number', models.CharField(max_length=10, null=True)),
                ('capacity', models.IntegerField(default=4, editable=False)),
                ('attempts', models.IntegerField(default=0)),
                ('available_digits_str', models.CharField(default='0123456789', max_length=10)),
                ('dual_game', models.BooleanField(default=True)),
                ('game_started', models.BooleanField(default=True)),
                ('new_game_requested', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('finish_time', models.DateTimeField(null=True)),
                ('upper_poster', models.CharField(max_length=250, null=True)),
                ('result_code', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YourHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=3), null=True, size=None)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', to_field='game_id')),
            ],
            options={
                'db_table': 'your_history',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='TotalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), null=True, size=None)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', to_field='game_id')),
            ],
            options={
                'db_table': 'total_set',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=3), null=True, size=None)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', to_field='game_id')),
            ],
            options={
                'db_table': 'my_history',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='FixtureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.IntegerField()),
                ('attempts', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'fixture_list',
                'ordering': ['id'],
            },
        ),
    ]
