# Generated by Django 4.0.3 on 2022-05-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=250, unique=True)),
                ('my_bulls', models.IntegerField(blank=True)),
                ('my_cows', models.IntegerField(blank=True)),
                ('your_bulls', models.IntegerField(blank=True)),
                ('your_cows', models.IntegerField(blank=True)),
                ('my_guess', models.IntegerField(blank=True)),
                ('your_guess', models.IntegerField(blank=True)),
                ('your_number', models.IntegerField(blank=True)),
                ('capacity', models.IntegerField(default=4)),
                ('dual_game', models.BooleanField(default=True)),
                ('game_started', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('finish_time', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'game',
                'ordering': ['game_id'],
            },
        ),
    ]
