# Generated by Django 4.0.3 on 2022-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='capacity',
            field=models.IntegerField(default=5),
        ),
    ]
