# Generated by Django 4.0.3 on 2022-08-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_privileges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_id']},
        ),
        migrations.AlterModelTable(
            name='game',
            table='game',
        ),
    ]
