# Generated by Django 4.0.3 on 2022-05-11 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
    ]
