# Generated by Django 4.0.3 on 2022-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_bulls',
            field=models.IntegerField(default=1),
        ),
    ]
