# Generated by Django 4.0.3 on 2022-05-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_my_bulls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='my_bulls',
            field=models.IntegerField(null=True),
        ),
    ]
