# Generated by Django 4.0.3 on 2022-05-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_my_bulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='dual_game',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_started',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='my_bulls',
            field=models.IntegerField(default=5, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='my_cows',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='my_guess',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='your_bulls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='your_cows',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='your_guess',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='your_number',
            field=models.IntegerField(null=True),
        ),
    ]
