# Generated by Django 4.0.3 on 2022-10-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_userext'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='middle_name',
            field=models.CharField(default='L', max_length=10),
        ),
    ]
