# Generated by Django 4.0.3 on 2022-05-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_finish_time_game_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='capacity',
            field=models.IntegerField(default=5, editable=False),
        ),
    ]
