# Generated by Django 4.0.3 on 2022-10-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_userext_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userext',
            name='middle_name',
        ),
    ]
