# Generated by Django 4.0.3 on 2022-10-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_userext_middle_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExt',
        ),
    ]
