# Generated by Django 4.0.3 on 2022-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='new_game_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='capacity',
            field=models.IntegerField(default=4, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='dual_game',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_started',
            field=models.BooleanField(default=True),
        ),
    ]
