# Generated by Django 4.0.3 on 2022-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_new_game_requested_alter_game_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
