# Generated by Django 4.0.3 on 2022-10-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_delete_userext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
