# Generated by Django 4.0.3 on 2022-05-16 16:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='available_digits_str',
            field=models.CharField(default='0123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='my_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='YourHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3), size=None)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'db_table': 'your_history',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='TotalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'db_table': 'total_set',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=3), size=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'db_table': 'my_history',
                'ordering': ['game_id'],
            },
        ),
        migrations.CreateModel(
            name='CurrentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
            options={
                'db_table': 'current_set',
                'ordering': ['game_id'],
            },
        ),
    ]
