# Generated by Django 4.0.3 on 2022-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_game_result_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='elapsed',
            field=models.IntegerField(default=0),
        ),
    ]
